import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import AuthProvider from "./auth/provider";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "RealMadrid - FC",
  description: "Generated by RealMadrid FC fans",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
       <body className={inter.className}>
        <AuthProvider>
        <main className="p-5">
            {children}
        </main>
          </AuthProvider>
      </body>
    </html>
  );
}
